import type { SceneNode, ScenePreset, CubeGridParams, LineGridParams, PlaneGridParams, AutomataGridParams } from './types';
import { DEFAULT_TRANSFORM, DEFAULT_SLICING, DEFAULT_CUBE_GRID_PARAMS, DEFAULT_LINE_GRID_PARAMS, DEFAULT_PLANE_GRID_PARAMS, DEFAULT_AUTOMATA_GRID_PARAMS } from './types';

// =============================================================================
// Scene Presets: one-click example scenes
// =============================================================================

const t = DEFAULT_TRANSFORM;
const s = DEFAULT_SLICING;

export const PRESETS: ScenePreset[] = [
  {
    name: 'Cube',
    description: 'Simple wireframe cube',
    icon: '\u25FB',
    create: () => [
      {
        name: 'Cube',
        type: 'cube',
        params: { min: [-1, -1, -1] as [number, number, number], max: [1, 1, 1] as [number, number, number] },
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'CSG Carve',
    description: 'Sphere carved from cube',
    icon: '\u2296',
    create: () => {
      const nodes: Omit<SceneNode, 'id'>[] = [
        {
          name: 'Outer Cube',
          type: 'cube',
          params: { min: [-1, -1, -1] as [number, number, number], max: [1, 1, 1] as [number, number, number] },
          transform: { ...t },
          visible: true,
          slicing: { ...s },
        },
        {
          name: 'Inner Sphere',
          type: 'sphere',
          params: { center: [0, 0, 0] as [number, number, number], radius: 1.35 },
          transform: { ...t },
          visible: true,
          slicing: { ...s },
        },
      ];
      return nodes;
    },
  },
  {
    name: 'Wave Surface',
    description: 'Mathematical sin/cos surface',
    icon: '\u223F',
    create: () => [
      {
        name: 'Wave',
        type: 'function',
        params: {
          expression: 'Math.sin(x * 2) * Math.cos(y * 2) * 0.5',
          bounds: {
            min: [-4, -4, -2] as [number, number, number],
            max: [4, 4, 2] as [number, number, number],
          },
          direction: 'below' as const,
        },
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Point Cloud',
    description: 'Fibonacci sphere distribution',
    icon: '\u2022',
    create: () => [
      {
        name: 'Fibonacci Cloud',
        type: 'point-cloud',
        params: {
          points: [],
          pointSize: 0.03,
          pattern: 'fibonacci-sphere' as const,
          count: 300,
          radius: 1.5,
          gridSpacing: 0.3,
        },
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Composition',
    description: 'Multiple shapes arranged together',
    icon: '\u2726',
    create: () => {
      const nodes: Omit<SceneNode, 'id'>[] = [];
      for (let i = 0; i < 5; i++) {
        const angle = (i / 5) * Math.PI * 2;
        nodes.push({
          name: `Cube ${i + 1}`,
          type: 'cube',
          params: {
            min: [-0.4, -0.4, -0.4] as [number, number, number],
            max: [0.4, 0.4, 0.4] as [number, number, number],
          },
          transform: {
            translate: [
              Math.cos(angle) * 2,
              Math.sin(angle) * 2,
              0,
            ] as [number, number, number],
            rotate: [0, 0, (angle * 180) / Math.PI] as [number, number, number],
            scale: [1, 1, 1] as [number, number, number],
          },
          visible: true,
          slicing: { ...s },
        });
      }
      // Center sphere
      nodes.push({
        name: 'Center Sphere',
        type: 'sphere',
        params: { center: [0, 0, 0] as [number, number, number], radius: 0.8 },
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      });
      return nodes;
    },
  },
  {
    name: 'Cylinder Stack',
    description: 'Stacked cylinders and cones',
    icon: '\u25B3',
    create: () => [
      {
        name: 'Base Cylinder',
        type: 'cylinder',
        params: { radius: 1, z0: -1, z1: 0 },
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
      {
        name: 'Middle Cylinder',
        type: 'cylinder',
        params: { radius: 0.7, z0: 0, z1: 0.8 },
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
      {
        name: 'Top Cone',
        type: 'cone',
        params: { radius: 0.5, height: 1.2 },
        transform: {
          translate: [0, 0, 0.8] as [number, number, number],
          rotate: [0, 0, 0] as [number, number, number],
          scale: [1, 1, 1] as [number, number, number],
        },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Sliced Sphere',
    description: 'Sphere with cross-section slices',
    icon: '\u2261',
    create: () => [
      {
        name: 'Sliced Sphere',
        type: 'sphere',
        params: { center: [0, 0, 0] as [number, number, number], radius: 1.5 },
        transform: { ...t },
        visible: true,
        slicing: { enabled: true, axis: 'z' as const, count: 8, gap: 0 },
      },
    ],
  },

  // --- Cube Grid Presets ---
  {
    name: 'Noise Grid',
    description: '3D grid with fractal noise sizing',
    icon: '\u2593',
    create: () => [
      {
        name: 'Noise Grid',
        type: 'cube-grid',
        params: {
          ...DEFAULT_CUBE_GRID_PARAMS,
          dimensions: '3d',
          countX: 6, countY: 6, countZ: 6,
          spacing: 0.5,
          sizeMethod: 'noise',
          sizeMin: 0.02,
          sizeMax: 0.38,
          noiseScale: 1.2,
          noiseSeed: 42,
          presenceMethod: 'threshold',
          presenceThreshold: 0.12,
        } satisfies CubeGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Radial Grid',
    description: 'Cubes sized by distance from center',
    icon: '\u25CE',
    create: () => [
      {
        name: 'Radial Grid',
        type: 'cube-grid',
        params: {
          ...DEFAULT_CUBE_GRID_PARAMS,
          dimensions: '3d',
          countX: 7, countY: 7, countZ: 7,
          spacing: 0.45,
          sizeMethod: 'radial',
          sizeMin: 0.02,
          sizeMax: 0.35,
          presenceMethod: 'sphere-mask',
        } satisfies CubeGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Sine Grid 2D',
    description: 'Flat grid with sine wave modulation',
    icon: '\u223F',
    create: () => [
      {
        name: 'Sine Grid 2D',
        type: 'cube-grid',
        params: {
          ...DEFAULT_CUBE_GRID_PARAMS,
          dimensions: '2d',
          countX: 12, countY: 12, countZ: 1,
          spacing: 0.45,
          sizeMethod: 'sine',
          sizeMin: 0.05,
          sizeMax: 0.35,
          sineFrequency: [3, 3, 1] as [number, number, number],
          presenceMethod: 'all',
        } satisfies CubeGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Scatter Grid',
    description: 'Random presence + random sizes',
    icon: '\u2591',
    create: () => [
      {
        name: 'Scatter Grid',
        type: 'cube-grid',
        params: {
          ...DEFAULT_CUBE_GRID_PARAMS,
          dimensions: '3d',
          countX: 8, countY: 8, countZ: 8,
          spacing: 0.4,
          sizeMethod: 'random',
          sizeMin: 0.05,
          sizeMax: 0.3,
          noiseSeed: 77,
          presenceMethod: 'random',
          presenceProbability: 0.35,
        } satisfies CubeGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Checker Volume',
    description: '3D checkerboard pattern',
    icon: '\u2B1A',
    create: () => [
      {
        name: 'Checker Volume',
        type: 'cube-grid',
        params: {
          ...DEFAULT_CUBE_GRID_PARAMS,
          dimensions: '3d',
          countX: 6, countY: 6, countZ: 6,
          spacing: 0.5,
          sizeMethod: 'uniform',
          sizeMin: 0.35,
          sizeMax: 0.35,
          presenceMethod: 'checkerboard',
        } satisfies CubeGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },

  // --- Voxel Shape Presets ---
  {
    name: 'Voxel Pyramid',
    description: 'Pyramid built from cubes',
    icon: '\u25B2',
    create: () => [
      {
        name: 'Voxel Pyramid',
        type: 'cube-grid',
        params: {
          ...DEFAULT_CUBE_GRID_PARAMS,
          dimensions: '3d',
          countX: 10, countY: 10, countZ: 10,
          spacing: 0.35,
          sizeMethod: 'uniform',
          sizeMin: 0.28,
          sizeMax: 0.28,
          presenceMethod: 'voxel-pyramid',
          voxelShellOnly: false,
        } satisfies CubeGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Voxel Torus',
    description: 'Torus (donut) from cubes',
    icon: '\u25EF',
    create: () => [
      {
        name: 'Voxel Torus',
        type: 'cube-grid',
        params: {
          ...DEFAULT_CUBE_GRID_PARAMS,
          dimensions: '3d',
          countX: 12, countY: 12, countZ: 8,
          spacing: 0.32,
          sizeMethod: 'uniform',
          sizeMin: 0.24,
          sizeMax: 0.24,
          presenceMethod: 'voxel-torus',
          voxelShellOnly: false,
        } satisfies CubeGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Voxel Diamond',
    description: 'Octahedron / diamond form',
    icon: '\u25C6',
    create: () => [
      {
        name: 'Voxel Diamond',
        type: 'cube-grid',
        params: {
          ...DEFAULT_CUBE_GRID_PARAMS,
          dimensions: '3d',
          countX: 9, countY: 9, countZ: 9,
          spacing: 0.38,
          sizeMethod: 'manhattan',
          sizeMin: 0.08,
          sizeMax: 0.3,
          presenceMethod: 'voxel-diamond',
          voxelShellOnly: false,
        } satisfies CubeGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Voxel Cross',
    description: '3D cross / plus from cubes',
    icon: '\u271A',
    create: () => [
      {
        name: 'Voxel Cross',
        type: 'cube-grid',
        params: {
          ...DEFAULT_CUBE_GRID_PARAMS,
          dimensions: '3d',
          countX: 9, countY: 9, countZ: 9,
          spacing: 0.38,
          sizeMethod: 'uniform',
          sizeMin: 0.3,
          sizeMax: 0.3,
          presenceMethod: 'voxel-cross',
          voxelShellOnly: false,
        } satisfies CubeGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Voxel Letter',
    description: '3D extruded letter A',
    icon: 'A',
    create: () => [
      {
        name: 'Voxel A',
        type: 'cube-grid',
        params: {
          ...DEFAULT_CUBE_GRID_PARAMS,
          dimensions: '3d',
          countX: 15, countY: 3, countZ: 21,
          spacing: 0.2,
          sizeMethod: 'uniform',
          sizeMin: 0.16,
          sizeMax: 0.16,
          presenceMethod: 'voxel-letter',
          voxelLetter: 'A',
          voxelShellOnly: false,
        } satisfies CubeGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Voxel Phrase',
    description: '3D extruded text phrase',
    icon: '\u2263',
    create: () => [
      {
        name: 'Voxel HELLO',
        type: 'cube-grid',
        params: {
          ...DEFAULT_CUBE_GRID_PARAMS,
          dimensions: '3d',
          countX: 29, countY: 3, countZ: 21,
          spacing: 0.15,
          sizeMethod: 'uniform',
          sizeMin: 0.12,
          sizeMax: 0.12,
          presenceMethod: 'voxel-letter',
          voxelLetter: 'HELLO',
          voxelShellOnly: false,
        } satisfies CubeGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Hollow Sphere',
    description: 'Sphere shell from cubes',
    icon: '\u25CB',
    create: () => [
      {
        name: 'Hollow Sphere',
        type: 'cube-grid',
        params: {
          ...DEFAULT_CUBE_GRID_PARAMS,
          dimensions: '3d',
          countX: 12, countY: 12, countZ: 12,
          spacing: 0.3,
          sizeMethod: 'uniform',
          sizeMin: 0.2,
          sizeMax: 0.2,
          presenceMethod: 'sphere-mask',
          voxelShellOnly: true,
        } satisfies CubeGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Staircase Grid',
    description: 'Quantized terraced cubes',
    icon: '\u2587',
    create: () => [
      {
        name: 'Staircase',
        type: 'cube-grid',
        params: {
          ...DEFAULT_CUBE_GRID_PARAMS,
          dimensions: '3d',
          countX: 8, countY: 8, countZ: 8,
          spacing: 0.4,
          sizeMethod: 'step',
          sizeMin: 0.04,
          sizeMax: 0.32,
          stepCount: 5,
          presenceMethod: 'all',
        } satisfies CubeGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Ripple Grid',
    description: 'Concentric wave pattern',
    icon: '\u25CE',
    create: () => [
      {
        name: 'Ripple Grid',
        type: 'cube-grid',
        params: {
          ...DEFAULT_CUBE_GRID_PARAMS,
          dimensions: '2d',
          countX: 16, countY: 16, countZ: 1,
          spacing: 0.35,
          sizeMethod: 'ripple',
          sizeMin: 0.02,
          sizeMax: 0.3,
          sineFrequency: [6, 6, 1] as [number, number, number],
          presenceMethod: 'all',
        } satisfies CubeGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },

  // --- Complex Generator Presets ---
  {
    name: 'Menger Sponge',
    description: 'Recursive fractal cube (depth 2, ~320 cubes)',
    icon: '\u25A3',
    create: () => [
      {
        name: 'Menger Sponge',
        type: 'cube-grid',
        params: {
          ...DEFAULT_CUBE_GRID_PARAMS,
          dimensions: '3d',
          countX: 9, countY: 9, countZ: 9,
          spacing: 0.4,
          sizeMethod: 'uniform',
          sizeMin: 0.32,
          sizeMax: 0.32,
          presenceMethod: 'menger-sponge',
          mengerDepth: 2,
          voxelShellOnly: false,
        } satisfies CubeGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Menger Shell',
    description: 'Menger sponge surface only (~200 cubes)',
    icon: '\u25A2',
    create: () => [
      {
        name: 'Menger Shell',
        type: 'cube-grid',
        params: {
          ...DEFAULT_CUBE_GRID_PARAMS,
          dimensions: '3d',
          countX: 9, countY: 9, countZ: 9,
          spacing: 0.4,
          sizeMethod: 'uniform',
          sizeMin: 0.32,
          sizeMax: 0.32,
          presenceMethod: 'menger-sponge',
          mengerDepth: 2,
          voxelShellOnly: true,
        } satisfies CubeGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'City Skyline',
    description: 'Random buildings (~300 cubes)',
    icon: '\u{1F3D9}',
    create: () => [
      {
        name: 'City Skyline',
        type: 'cube-grid',
        params: {
          ...DEFAULT_CUBE_GRID_PARAMS,
          dimensions: '3d',
          countX: 6, countY: 6, countZ: 10,
          spacing: 0.55,
          sizeMethod: 'uniform',
          sizeMin: 0.45,
          sizeMax: 0.45,
          presenceMethod: 'city-skyline',
          cityMinHeight: 1,
          cityMaxHeight: 9,
          citySeed: 42,
        } satisfies CubeGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Dense City',
    description: 'Tightly packed cityscape (~400 cubes)',
    icon: '\u{1F3E2}',
    create: () => [
      {
        name: 'Dense City',
        type: 'cube-grid',
        params: {
          ...DEFAULT_CUBE_GRID_PARAMS,
          dimensions: '3d',
          countX: 8, countY: 8, countZ: 12,
          spacing: 0.42,
          sizeMethod: 'random',
          sizeMin: 0.2,
          sizeMax: 0.36,
          noiseSeed: 77,
          presenceMethod: 'city-skyline',
          cityMinHeight: 2,
          cityMaxHeight: 10,
          citySeed: 99,
        } satisfies CubeGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Voxel Terrain',
    description: 'Noise heightmap landscape (~250 cubes)',
    icon: '\u26F0',
    create: () => [
      {
        name: 'Voxel Terrain',
        type: 'cube-grid',
        params: {
          ...DEFAULT_CUBE_GRID_PARAMS,
          dimensions: '3d',
          countX: 10, countY: 10, countZ: 6,
          spacing: 0.38,
          sizeMethod: 'uniform',
          sizeMin: 0.3,
          sizeMax: 0.3,
          presenceMethod: 'heightmap',
          heightmapScale: 0.5,
          heightmapSeed: 42,
          heightmapOctaves: 3,
        } satisfies CubeGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Mountain Range',
    description: 'Dramatic voxel peaks (~350 cubes)',
    icon: '\u{1F3D4}',
    create: () => [
      {
        name: 'Mountain Range',
        type: 'cube-grid',
        params: {
          ...DEFAULT_CUBE_GRID_PARAMS,
          dimensions: '3d',
          countX: 12, countY: 12, countZ: 8,
          spacing: 0.32,
          sizeMethod: 'uniform',
          sizeMin: 0.26,
          sizeMax: 0.26,
          presenceMethod: 'heightmap',
          heightmapScale: 0.3,
          heightmapSeed: 7,
          heightmapOctaves: 4,
        } satisfies CubeGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: '3D Maze',
    description: 'Procedural maze (~200 cubes)',
    icon: '\u2395',
    create: () => [
      {
        name: '3D Maze',
        type: 'cube-grid',
        params: {
          ...DEFAULT_CUBE_GRID_PARAMS,
          dimensions: '3d',
          countX: 13, countY: 13, countZ: 3,
          spacing: 0.3,
          sizeMethod: 'uniform',
          sizeMin: 0.24,
          sizeMax: 0.24,
          presenceMethod: 'maze',
          mazeSeed: 42,
          mazeWallThickness: 1,
        } satisfies CubeGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Tall Maze',
    description: 'Deep maze with high walls (~350 cubes)',
    icon: '\u2687',
    create: () => [
      {
        name: 'Tall Maze',
        type: 'cube-grid',
        params: {
          ...DEFAULT_CUBE_GRID_PARAMS,
          dimensions: '3d',
          countX: 11, countY: 11, countZ: 5,
          spacing: 0.34,
          sizeMethod: 'uniform',
          sizeMin: 0.28,
          sizeMax: 0.28,
          presenceMethod: 'maze',
          mazeSeed: 13,
          mazeWallThickness: 1,
        } satisfies CubeGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },

  // --- Plane Grid Presets ---
  {
    name: 'Stacked Planes',
    description: 'Uniform thin rectangles stacked in Z',
    icon: '\u25AD',
    create: () => [
      {
        name: 'Stacked Planes',
        type: 'plane-grid',
        params: {
          ...DEFAULT_PLANE_GRID_PARAMS,
          count: 15,
          stackAxis: 'z',
          spacing: 0.22,
          planeWidth: 3,
          planeHeight: 3,
          thickness: 0.02,
          sizeMethod: 'uniform',
        } satisfies PlaneGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Noise Planes',
    description: 'Planes with noise-driven sizes',
    icon: '\u25AF',
    create: () => [
      {
        name: 'Noise Planes',
        type: 'plane-grid',
        params: {
          ...DEFAULT_PLANE_GRID_PARAMS,
          count: 20,
          stackAxis: 'z',
          spacing: 0.18,
          planeWidth: 3.5,
          planeHeight: 3.5,
          thickness: 0.02,
          sizeMethod: 'noise',
          sizeMin: 0.15,
          sizeMax: 1.0,
          noiseSeed: 42,
          noiseScale: 0.6,
          anisotropic: false,
        } satisfies PlaneGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Aniso Planes',
    description: 'Width & height vary independently',
    icon: '\u25A1',
    create: () => [
      {
        name: 'Aniso Planes',
        type: 'plane-grid',
        params: {
          ...DEFAULT_PLANE_GRID_PARAMS,
          count: 18,
          stackAxis: 'z',
          spacing: 0.2,
          planeWidth: 3,
          planeHeight: 3,
          thickness: 0.02,
          sizeMethod: 'noise',
          sizeMin: 0.1,
          sizeMax: 1.0,
          noiseSeed: 77,
          noiseScale: 0.5,
          anisotropic: true,
        } satisfies PlaneGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Radial Planes',
    description: 'Largest in center, smallest at edges',
    icon: '\u25CE',
    create: () => [
      {
        name: 'Radial Planes',
        type: 'plane-grid',
        params: {
          ...DEFAULT_PLANE_GRID_PARAMS,
          count: 16,
          stackAxis: 'z',
          spacing: 0.22,
          planeWidth: 4,
          planeHeight: 4,
          thickness: 0.015,
          sizeMethod: 'radial',
          sizeMin: 0.1,
          sizeMax: 1.0,
        } satisfies PlaneGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Sine Planes',
    description: 'Sine wave pulsing through the stack',
    icon: '\u223F',
    create: () => [
      {
        name: 'Sine Planes',
        type: 'plane-grid',
        params: {
          ...DEFAULT_PLANE_GRID_PARAMS,
          count: 24,
          stackAxis: 'z',
          spacing: 0.15,
          planeWidth: 3,
          planeHeight: 3,
          thickness: 0.015,
          sizeMethod: 'sine',
          sizeMin: 0.15,
          sizeMax: 1.0,
          sineFreq: 1.5,
        } satisfies PlaneGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },

  // --- Line Grid Presets ---
  {
    name: 'Line Grid',
    description: 'Grid of vertical lines',
    icon: '\u2502',
    create: () => [
      {
        name: 'Line Grid',
        type: 'line-grid',
        params: {
          ...DEFAULT_LINE_GRID_PARAMS,
          countX: 12,
          countY: 12,
          lineLength: 2,
          spacing: 0.3,
          lineAxis: 'z',
        } satisfies LineGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Line Forest',
    description: 'Dense field of tall lines',
    icon: '\u2503',
    create: () => [
      {
        name: 'Line Forest',
        type: 'line-grid',
        params: {
          ...DEFAULT_LINE_GRID_PARAMS,
          countX: 20,
          countY: 20,
          lineLength: 3,
          spacing: 0.2,
          lineAxis: 'z',
        } satisfies LineGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Noise Lines',
    description: 'Line lengths driven by noise',
    icon: '\u2551',
    create: () => [
      {
        name: 'Noise Lines',
        type: 'line-grid',
        params: {
          ...DEFAULT_LINE_GRID_PARAMS,
          countX: 16,
          countY: 16,
          spacing: 0.25,
          lineAxis: 'z',
          lengthMethod: 'noise',
          lengthMin: 0.2,
          lengthMax: 2.5,
          lengthSeed: 42,
          lengthNoiseScale: 0.8,
        } satisfies LineGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Pin Art Noise',
    description: 'Pin art with noise-driven surface',
    icon: '\u2506',
    create: () => [
      {
        name: 'Pin Art Noise',
        type: 'line-grid',
        params: {
          ...DEFAULT_LINE_GRID_PARAMS,
          countX: 16,
          countY: 16,
          lineLength: 2.5,
          spacing: 0.22,
          lineAxis: 'z',
          lengthMethod: 'noise',
          lengthMin: 0.3,
          lengthMax: 2.0,
          lengthSeed: 42,
          lengthNoiseScale: 0.6,
          segmented: true,
          gapSize: 0.15,
        } satisfies LineGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Pin Art Radial',
    description: 'Pin art with radial impression',
    icon: '\u25D4',
    create: () => [
      {
        name: 'Pin Art Radial',
        type: 'line-grid',
        params: {
          ...DEFAULT_LINE_GRID_PARAMS,
          countX: 18,
          countY: 18,
          lineLength: 3.0,
          spacing: 0.2,
          lineAxis: 'z',
          lengthMethod: 'radial',
          lengthMin: 0.4,
          lengthMax: 2.6,
          segmented: true,
          gapSize: 0.12,
        } satisfies LineGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Pin Art Sine',
    description: 'Pin art with sine wave surface',
    icon: '\u2248',
    create: () => [
      {
        name: 'Pin Art Sine',
        type: 'line-grid',
        params: {
          ...DEFAULT_LINE_GRID_PARAMS,
          countX: 16,
          countY: 16,
          lineLength: 2.5,
          spacing: 0.24,
          lineAxis: 'z',
          lengthMethod: 'sine',
          lengthMin: 0.3,
          lengthMax: 2.0,
          lengthSineFreq: 1.5,
          segmented: true,
          gapSize: 0.12,
        } satisfies LineGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Radial Lines',
    description: 'Line lengths diminish from center',
    icon: '\u25D8',
    create: () => [
      {
        name: 'Radial Lines',
        type: 'line-grid',
        params: {
          ...DEFAULT_LINE_GRID_PARAMS,
          countX: 18,
          countY: 18,
          spacing: 0.22,
          lineAxis: 'z',
          lengthMethod: 'radial',
          lengthMin: 0.1,
          lengthMax: 3.0,
        } satisfies LineGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Lines + Cubes',
    description: 'Line grid with cube grid overlay',
    icon: '\u256C',
    create: () => [
      {
        name: 'Lines',
        type: 'line-grid',
        params: {
          ...DEFAULT_LINE_GRID_PARAMS,
          countX: 8,
          countY: 8,
          lineLength: 3,
          spacing: 0.4,
          lineAxis: 'z',
        } satisfies LineGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
      {
        name: 'Cubes',
        type: 'cube-grid',
        params: {
          ...DEFAULT_CUBE_GRID_PARAMS,
          dimensions: '3d',
          countX: 4, countY: 4, countZ: 4,
          spacing: 0.8,
          sizeMethod: 'noise',
          sizeMin: 0.1,
          sizeMax: 0.5,
          noiseScale: 1.5,
          noiseSeed: 13,
          presenceMethod: 'sphere-mask',
        } satisfies CubeGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },

  // --- Cellular Automata Presets ---
  {
    name: 'Conway Life',
    description: "Conway's Game of Life stacked in 3D",
    icon: '\u2637',
    create: () => [
      {
        name: 'Conway Life',
        type: 'automata-grid',
        params: {
          ...DEFAULT_AUTOMATA_GRID_PARAMS,
          gridWidth: 16,
          gridHeight: 16,
          generations: 20,
          spacing: 0.22,
          cubeSize: 0.18,
          rule: 'B3/S23',
          initialPattern: 'r-pentomino',
          seed: 42,
        } satisfies AutomataGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Maze Growth',
    description: 'Maze rule generates labyrinthine layers',
    icon: '\u2592',
    create: () => [
      {
        name: 'Maze Growth',
        type: 'automata-grid',
        params: {
          ...DEFAULT_AUTOMATA_GRID_PARAMS,
          gridWidth: 20,
          gridHeight: 20,
          generations: 12,
          spacing: 0.18,
          cubeSize: 0.14,
          rule: 'B3/S12345',
          initialPattern: 'center',
          seed: 7,
        } satisfies AutomataGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'HighLife',
    description: 'HighLife rule with replicator patterns',
    icon: '\u2726',
    create: () => [
      {
        name: 'HighLife',
        type: 'automata-grid',
        params: {
          ...DEFAULT_AUTOMATA_GRID_PARAMS,
          gridWidth: 18,
          gridHeight: 18,
          generations: 16,
          spacing: 0.2,
          cubeSize: 0.16,
          rule: 'B36/S23',
          initialPattern: 'random',
          randomDensity: 0.25,
          seed: 99,
        } satisfies AutomataGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Seeds Explosion',
    description: 'Seeds rule — explosive, nothing survives',
    icon: '\u2734',
    create: () => [
      {
        name: 'Seeds',
        type: 'automata-grid',
        params: {
          ...DEFAULT_AUTOMATA_GRID_PARAMS,
          gridWidth: 20,
          gridHeight: 20,
          generations: 10,
          spacing: 0.18,
          cubeSize: 0.14,
          rule: 'B2/S',
          initialPattern: 'center',
          seed: 1,
        } satisfies AutomataGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
  {
    name: 'Glider Tower',
    description: 'Single glider traced through time',
    icon: '\u2197',
    create: () => [
      {
        name: 'Glider Tower',
        type: 'automata-grid',
        params: {
          ...DEFAULT_AUTOMATA_GRID_PARAMS,
          gridWidth: 12,
          gridHeight: 12,
          generations: 30,
          spacing: 0.25,
          cubeSize: 0.2,
          rule: 'B3/S23',
          initialPattern: 'glider',
          seed: 0,
          wrapEdges: true,
        } satisfies AutomataGridParams,
        transform: { ...t },
        visible: true,
        slicing: { ...s },
      },
    ],
  },
];
